### ISSUE TITLE
Add https://arrow.apache.org/go/

### ISSUE THREAD

**Issue by kou** [apache/arrow-go#139]
We can maintain the URL in this repository by adding the following configuration to `.asf.yaml`:

```yaml
publish:
  whoami: asf-site
  subdir: go
```

The `asf-site` content will be deployed to `https://arrow.apache.org/go/` automatically.
